# Generated by Django 4.2.9 on 2024-07-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
