# Generated by Django 4.2.9 on 2024-07-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
