# Generated by Django 4.2.9 on 2024-08-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0008_gamehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_game', 'In Game'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
    ]
