# Generated by Django 4.2.9 on 2024-08-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0011_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
